# Generated by Django 4.0.1 on 2022-01-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(default='Quantity = 1, Date added:2022-01-12')),
                ('price', models.FloatField(default=1.99, max_length=20)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
