# Generated by Django 4.0.1 on 2022-01-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default=True)),
                ('price', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
