# Generated by Django 4.0.1 on 2022-01-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_product_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(max_length=20),
        ),
    ]
