# Generated by Django 4.0.1 on 2022-01-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Date added:<built-in method today of type object at 0x1077c9a00>'),
        ),
    ]
