# Generated by Django 4.0.1 on 2022-01-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1.99, max_length=20),
        ),
    ]
