# Generated by Django 4.0.1 on 2022-01-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
